Adding $priority to the NormalizersRegistryInterface
spiral-packages/symfony-serializer pull request #22
Opened 2023-04-19 13:39 UTC by msmakouz

### Features

1) Added the **priority** parameter to the `register` method of the interface
    `Spiral\Serializer\Symfony\NormalizersRegistryInterface`. This will allow normalizers and denormalizers
    to be registered in the correct order. Default ones are added with a priority that allows you to add your own
    between them.

```php
// add custom normalizer BEFORE all default normalizers
$registry->register(new CustomNormalizer(), 1);
```

### Bugfixes

1) Fixed nested objects serialization.

2023-04-19 13:54 UTC, butschster approved these changes

2023-04-19 13:55 UTC, butschster commented
Could you fix Readme

- normalizers
- serializer names
- requirements

2023-04-19 13:56 UTC, butschster requested changes
Could you fix Readme

normalizers
serializer names
requirements

2023-04-19 14:21 UTC, msmakouz commented
> Could you fix Readme
> 
> normalizers serializer names requirements

Updated

2023-04-20 05:25 UTC, butschster approved these changes

2023-04-20 05:26 UTC, butschster approved these changes

2023-04-20 05:26 UTC, merged